### PR TITLE
MDL 104-106 and Zork executables from Rich Alderson

### PR DESCRIPTION
**Pull request by atsampson**
Downloaded from LCM+L's TOAD-2, using ckermit talking to TOPS-20 kermit with `set file 7-bit` on, to give ANSI-ASCII output.

MDL104 and MDL105 both complain about the GC not being available on startup (although the AGC file is there for 104, probably just not in the right place). MDL106 starts up OK but complains about the GC if you cause a garbage collection.

Zork is for MDL104 and works.

### CODE REVIEW

**Comment by eswenson1** [comment]
I assume that when you say Zork works, you mean using a TOPS-20 MUddle executable? And that we don't yet have an ITS Muddle that will run Zork successfully?

**Review by larsbrinkhoff — APPROVED** [review]
Not much to review here, but approved just in case.

**Comment by atsampson** [comment]
Yes, I mean it works on TOPS-20, I'm afraid!

It's a different set of files from the Zork in the Panda distribution, which uses Muddle 105.

**Comment by ZoBoRf** [comment]
There is a problem with `MDL104.EXE` (the only one here with an gc).
To load it I have to say: 
```
DEFINE MDL: TOPS20:<ROB>
```
where `<ROB>` is my home dir. So far so good.
When I look into the exe I see near the end:
grafik

This are Metafont source letters from Knuth's "Computer Modern Typefaces".

I try nevertheless the creating, and writing a file:
```
@type filtst.mud
<SET CHAN <OPEN "PRINT" "DSK:<ROB>BAZ.TXT">>
<PRINC "Hamster was here!" .CHAN>
<CRLF .CHAN>
<PRINC "<EOF>" .CHAN>
<CRLF .CHAN>
<BUFOUT .CHAN>
<CLOSE .CHAN>
@mdl104
MUDDLE 104 IN OPERATION.
LISTENING-AT-LEVEL 1 PROCESS 1
<FLOAD "DSK:<ROB>FILTST.MUD">$

*ERROR*
#CHANNEL [3 "READ" "FILTST" "MUD" "DSK" "ROB" "FILTST" "MUD.14;P777700;A" 
"TOPS20" "ROB" 0 23085702444 #TIME *000000000025* 0 0 0 165 10 
""
]
"CHAR"
NOT-HANDLED
OFF
LISTENING-AT-LEVEL 2 PROCESS 1
```
There is a problem with the "CHAR" interrupt.
```
<ERRET T>$
"DONE"
<QUIT>
$
@type baz.txt
Hamster was here!
<EOF>
    
@
```
It sort of works, but is not enough. The "CHAR" NOT-HANDLED does not not happen in the other interpeters.
And it does not happen when one enters the lines from `filtst.mud` by hand...

**Comment by rmaldersoniii** [comment]
I don’t understand why that kermit setting worked; they are not 7-bit files.

If you look at ZORK.MAC, you will see that MDL104 (and its garbage collector) expect a logical name MDL: pointing to where they live.  Try defining that, and see if the AGC works for you.

Rich Alderson
github@alderson.users.panix.com <mailto:github@alderson.users.panix.com>
its@alderson.users.panix.com <mailto:its@alderson.users.panix.com>

**Comment by ZoBoRf** [comment]
Before the FTP transfer to TOPS-20 in binary mode I converted the github files e.g. `mdl104.exe` with `wfconv`
```
wfconv -ah <mdl104.exe >out/mdl104.exe
```
and transferred `out/mdl104.exe`.
After `DEFINE MDL: TOPS20:<ROB>`
`mdl104.exe` started, but has internal corruptions (see last message).

FYI:
```
Usage: wfconv -io <infile >outfile
  where 'i' and 'o' are chars specifying the input and output formats:
    c   - Core-dump  (std tape format, 4 8-bit, 1 4-bit bytes = 36 bits)
    h   - High-density (FTP 36-bit image, 9 8-bit bytes = 72 bits)
    a,7 - Ansi-Ascii (4 7-bit, 1 8-bit byte = 36 bits)
    s,6 - Sixbit     (6 6-bit bytes = 36 bits)
    u   - Unixified  (Alan Bawden format, various = 36 bits)
    t   - Text-Newline (CRLF-NL conversion; 5 7-bit bytes = 35 bits ONLY)
    d   - Debug (output only - show word values)
    D   - Debug (like -d with offsets)
  Note: EOF on input always zero-pads up to a PDP-10 word boundary.
```

**Comment by atsampson** [comment]
> I don’t understand why that kermit setting worked; they are not 7-bit files.

It wasn't immediately clear to me from the manual, but TOPS-20 Kermit's `set file 7-bit` preserves the 36th bit in ANSI-ASCII form for both sending and receiving. From the [source](http://www.columbia.edu/kermit/ftp/d/k20mit.mac):

```
; [...] Worry about bit 35 if doing 7-bit i/o.  The trick
; is to set the parity bit ("b8") of every 5th character to the value of b35
; of the PDP-10 word it came from.  The same trick is used by TOPS-20 when
; writing ANSI-ASCII tapes.  This allows DEC-10/20 .EXE and other 36-bit binary
; files, and SOS-line numbered files, to be sent to 8-bit systems and retrieved
; intact.  No adverse effects are suffered by ordinary text files.
```

Which is pretty handy...

**Pull request merged**
